name: FTP deployment

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn install
    - run: yarn build
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      with:
        # FTP server name (you may need to specify a port)
        FTP_SERVER: ractive.ch
        # FTP account username
        FTP_USERNAME: ractive
        # FTP account password
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        LOCAL_DIR: build
        # The remote folder to copy to, deafults to root FTP folder (I recommend you configure this on your server side instead of here)
        REMOTE_DIR: /subdomains/lego-remote/httpdocs/
